add es2015 maps
aikoven/typescript-immutable-utils pull request #3
Opened 2019-03-21 14:56 UTC by VladimirLogachev

Мы сделаем свои иммутабельные функторы, с ассоциативностью и идентичностями!

2019-03-21 15:11 UTC, aikoven requested changes

2019-03-21 15:11 UTC, aikoven commented on package.json
> +  "version": "0.1.2",
Не надо обновлять версию, я бампну при релизе

2019-03-21 15:11 UTC, aikoven commented on src/maps.ts
> +    Array.from(src.entries()).map(
Можно избежать создания доп массива, передавая маппер вторым аргументом в Array.from

2019-03-21 15:53 UTC, VladimirLogachev commented on src/maps.ts
> +    Array.from(src.entries()).map(
да. но мне нужна map, которая умеет в K.

2019-03-21 15:53 UTC, VladimirLogachev commented on package.json
> +  "version": "0.1.2",
переделал

2019-03-21 17:07 UTC, aikoven commented on src/maps.ts
> +    Array.from(src.entries()).map(
Я про то, что `Array.from(x).map(f)` эквивалентен `Array.from(x, f)`

2019-03-22 02:15 UTC, VladimirLogachev commented on src/maps.ts
> +    Array.from(src.entries()).map(
Понял. И там деструктурирую пару на k и v.

2019-03-22 04:55 UTC, VladimirLogachev commented on src/maps.ts
> +    Array.from(src.entries()).map(
Переделал

2019-03-22 05:47 UTC, aikoven approved these changes

2019-03-22 05:47 UTC, merged